# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_post_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='docfile',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='documents/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
