# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_auto_20160226_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='users_app.tag'),
        ),
    ]
