# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_auto_20160226_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.SlugField(default='no_fiels', max_length=40),
        ),
    ]
