# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 15:01
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
