# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0012_auto_20160226_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(default='', to='users_app.tag'),
        ),
    ]
