# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20160226_1455'),
        ('users_app', '0014_auto_20160226_1652'),
    ]

    operations = [
    ]
